#Server Properties
#debug: true
server:
  port: 9898
  servlet:
    context-path: /myapp
#Datasource Properties
spring:
#  datasource:
#    driver-class-name:


  h2:
    console:
      enabled: true
      
#View Resolver
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
      
#ORM
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#see logback-spring.xml in classpath: src/main/resources
logging:  level:#    root: off
#    root: OFF
    com.tekleads: debug
#    com.tekleads: OFF
  file:    name: C:\\Users\\Dissolve\\git\\nitproj\\logs\\Contact-App.log     